### ISSUE TITLE
How to solve the problem for convergence?

### ISSUE THREAD

**Issue by CaptainKai** [niliusha123/SubCenterArcFace#5]
For there is no upper bound for the final loss formulation, how do you solve the problem that loss is too large to start training?(loss is reported as NAN)

**Comment by niliusha123** [comment]
hi, these losses work like cross entropy,  so, if your loss as NAN, i think your labels(dataset) get wrong  that based on your network could output normally.

**Comment by CaptainKai** [comment]
Interestingly, Sphereface2 converges when deployed in resnet backbone while does not converge in that proposed in the article for sphereface
